#!/usr/bin/env bash

if [ "npm" == "$1" ]; then
	eval docker run --rm -ti -v ${PWD}:/app -e HOME=/app --user $(id -u):$(id -g) zealbyte/packer /bin/bash -c \"$@\"
elif [ "bower" == "$1" ]; then
	eval docker run --rm -ti -v ${PWD}:/app -e HOME=/app --user $(id -u):$(id -g) zealbyte/packer /bin/bash -c \"$@\"
elif [ "composer" == "$1" ]; then
	eval docker run --rm -ti -v ${PWD}:/app -e HOME=/app --user $(id -u):$(id -g) composer /bin/bash -c \"$@\"
elif [ "" == "$1" ]; then
	echo "No command was supplied"
else
	echo "$1 is not a valid docker container command."
fi
